# create a file named Dockerfile
FROM node:8.14-alpine

RUN mkdir /app

WORKDIR /app

# RUN npm install -g nodemon

# COPY package.json /app
# RUN npm install

# COPY . /app

EXPOSE 3000

CMD ["npm", "start"]