# create a file named Dockerfile
FROM node:latest

RUN mkdir /app

WORKDIR /app

# RUN npm install -g nodemon

# COPY package.json /app
# RUN npm install

# COPY . /app

EXPOSE 1234

CMD ["npm", "start"]